### PR TITLE
make FAQ card

### PR DESCRIPTION
**Pull request by liruochen1998**

### CODE REVIEW

**Comment by AdamWinek** [comment]
Looks great so far! I think next steps would be working on the mobile friendliness of the page, changing the position of the header to be consistent with the meet the team page and connecting to the netlify cms. Let me know if you have any questions about anything. If you want I can tackle the cms stuff as I have spent the most time doing that stuff.

**Comment by liruochen1998** [comment]
I'll start working on them, thanks! might need help on cms. It would be great if I can observe when you do it so that I can learn. Thanks!

**Comment by liruochen1998** [comment]
@AdamWinek just changed the header to be consistent -- I simply used the same stylesheet that MeetTheTeam used, which might not be best practice, but can be easily refactored later on. I think the page is already mobile-friendly without manual customization after I deleted the image, which I remembered that you mentioned might be discarded anyway.

**Comment by AdamWinek** [comment]
Looks great merging in the changes now!

**Pull request merged**
